apiVersion: v1
kind: Service
metadata:
  name: phoenix
  namespace: phoenix-check
spec:
  type: NodePort
  ports:
  - port: 9288
    protocol: TCP
    name: web-30567
  - port: 7375
    protocol: TCP
    name: xxl-30557
  selector:
    app: phoenix

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: phoenix
  namespace: phoenix-check
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: phoenix
    spec:
      containers:
      - name: phoenix
        image: hub.komect.com:10443/phoenix-check/phoenix:d7c3310d
        imagePullPolicy: Always
        env:   #容器环境变量设置，可以覆盖工程中的配置
        - name: spring.profiles.active
          value: "dev"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.2
            memory: 2Gi
      imagePullSecrets:
      - name: phoenix-image         
