apiVersion: v1
kind: Service
metadata:
  name: cube-project
  #填写自己的namespace
  namespace: mynamespace
spec:
  type: NodePort
  ports:
  - port: 9288
    protocol: TCP
    name: web-30567
  - port: 7375
    protocol: TCP
    name: xxl-30557
  selector:
    app: cube-project

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cube-project
  namespace: mynamespace
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cube-project
    spec:
      containers:
      - name: cube-project
        #镜像地址
        image: ip:port/mynamespace/cube-project:${version}
        imagePullPolicy: Always
        env:   #容器环境变量设置，可以覆盖工程中的配置
        - name: spring.profiles.active
          value: "dev"
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 0.2
            memory: 2Gi
      imagePullSecrets:
      - name: cube-project-image         
